[Valutazioni] Added shimmers, layout fixes + added a new segmentedcontrol
Gabboxl/ClassevivaPCTO pull request #174
Opened 2023-10-29 17:23 UTC by alessandrocaseti

- Aggiunto il pacchetto shimmer #172 
- Aggiunti gli shimmer, vanno solo creati i visibility converter
- Aggiunto il nuovo segmentecontrol #173 (va rimossa la checkbox)
- Layout fixes, adesso la listview è centrata nell'expander + corretto il placeholder

2023-10-29 17:24 UTC, alessandrocaseti commented
@Gabboxl siccome sono incomplete ho fatto un draft. Se riuscissi a creare quel visibility converter gli shimmer sono apposto

2023-11-01 14:00 UTC, alessandrocaseti commented
il segmentedcontol è pronto. Ho aggiunto come visibility converter quelli del progressring, ma ovviamente si attivano anche quando la pagina ricaricata col tasto refresh. Gli shimmer dovrebbero vedersi solo la prima volta che viene caricata la pagina. Inoltre il testo "Media totale" dovrebbe vedersi a caricamento completato per non sovrapporsi agli shimmer - quindi un converter inverso ad essi.

2023-11-11 12:52 UTC, Gabboxl requested changes

2023-11-11 12:52 UTC, Gabboxl commented on README.md
fare rebase e eliminare modifiche al readme, già integrate nel main

2023-11-11 12:55 UTC, Gabboxl commented
@alessandrocaseti andando avanti cerca di suddividere sempre di più ogni modifica in pull request/branch differenti per semplificare il lavoro. in questo caso sarebbe stato meglio dividere in due branch le modifiche per il segmented e gli shimmer, così anche per me la revisione delle modifiche diventa più semplice

2023-11-11 20:23 UTC, Gabboxl requested changes

2023-11-11 20:23 UTC, Gabboxl commented on ClassevivaPCTO/Views/Valutazioni.xaml
> +                            <RelativePanel
perchè sostituire il Grid con RelativePanel?

2023-11-11 20:53 UTC, alessandrocaseti commented on ClassevivaPCTO/Views/Valutazioni.xaml
> +                            <RelativePanel
con il grid la listview non si espandeva alla massima larghezza nell'expander e quindi non risultava centrata

2023-11-12 10:09 UTC, Gabboxl approved these changes

2023-11-12 10:10 UTC, merged