[StartUp v2] Nuova login page
Gabboxl/ClassevivaPCTO pull request #180
Opened 2023-11-10 14:23 UTC by alessandrocaseti

2023-11-11 12:59 UTC, alessandrocaseti commented
@Gabboxl siccome non è ancora pronta, non revisionarla. Volevo chiederti se potresti creare un branch sulla tua repo per la startup v2 così posso riclonare il mio fork dopo che le altre pr verranno approvate. Altrimenti chiudo questa e salvo le modifiche da un altra parte, dimmi cosa conviene fare

2023-11-11 13:53 UTC, Gabboxl commented
> @Gabboxl siccome non è ancora pronta, non revisionarla. Volevo chiederti se potresti creare un branch sulla tua repo per la startup v2 così posso riclonare il mio fork dopo che le altre pr verranno approvate. Altrimenti chiudo questa e salvo le modifiche da un altra parte, dimmi cosa conviene fare

scusami in realtà non ho capito bene il problema haha, non puoi semplicemente eliminare la tua repo locale e riclonare tutto?

2023-11-11 14:26 UTC, alessandrocaseti commented
> > @Gabboxl siccome non è ancora pronta, non revisionarla. Volevo chiederti se potresti creare un branch sulla tua repo per la startup v2 così posso riclonare il mio fork dopo che le altre pr verranno approvate. Altrimenti chiudo questa e salvo le modifiche da un altra parte, dimmi cosa conviene fare
> 
> scusami in realtà non ho capito bene il problema haha, se hai problemi in locale non puoi semplicemente eliminare la tua repo locale e riclonare tutto? Ormai le modifiche le hai già pushare qua sul server

per syncare il fork dovrei discardare i commit che ho in main (shimmer)

2023-11-11 15:39 UTC, Gabboxl commented
> > > @Gabboxl siccome non è ancora pronta, non revisionarla. Volevo chiederti se potresti creare un branch sulla tua repo per la startup v2 così posso riclonare il mio fork dopo che le altre pr verranno approvate. Altrimenti chiudo questa e salvo le modifiche da un altra parte, dimmi cosa conviene fare
> > 
> > 
> > scusami in realtà non ho capito bene il problema haha, se hai problemi in locale non puoi semplicemente eliminare la tua repo locale e riclonare tutto? Ormai le modifiche le hai già pushare qua sul server
> 
> per syncare il fork dovrei discardare i commit che ho in main (shimmer)

ahh okaay ora ho capito, usa questo comando per clonare il mio branch main in uno nuovo in locale:

`git checkout -b <nuovo_nome_branch> origin/main`

ricorda di creare sempre un nuovo branch per fare modifiche, usa il meno possibile il main

2023-11-22 23:37 UTC, Gabboxl commented
@alessandrocaseti Non mettiamo il pulsante di login demo, credo possa confondere gli utenti, lasciamo il login demo solo come un qualcosa di avanzato

2023-11-23 05:03 UTC, alessandrocaseti commented
> @alessandrocaseti Non mettiamo il pulsante di login demo, credo possa confondere gli utenti, lasciamo il login demo solo come un qualcosa di avanzato

sisi certo, l'intenzione è quella di commentare la parte xaml prima della release ufficiale, serve solo a noi

2023-12-16 17:13 UTC, alessandrocaseti commented
![Screenshot (257)](https://github.com/Gabboxl/ClassevivaPCTO/assets/90320229/c4eef2e9-ff00-41c0-8ba2-d5746ebb9b69)

parte 1 pronta. Nella parte due - creare un asset per il tema chiaro

2024-01-11 19:25 UTC, Gabboxl commented
> ![Screenshot (257)](https://private-user-images.githubusercontent.com/90320229/291006177-c4eef2e9-ff00-41c0-8ba2-d5746ebb9b69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMDEzMTMsIm5iZiI6MTcwNTAwMTAxMywicGF0aCI6Ii85MDMyMDIyOS8yOTEwMDYxNzctYzRlZWYyZTktZmYwMC00MWMwLThiYTItZDU3NDZlYmI5YjY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDE5MjMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkNTVlYzEyZjIxOGM5MWM4MGJjNTVlMGMwOTQ3MWRlMWYzYTIyNmZiMzYzMDNmNzc4YTU1Y2NiMGUxN2U4NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WouAgrcx_8BXEX-JJo_0eWQSWQm7jRGB9LwghFbDlD8)
> 
> parte 1 pronta. Nella parte due - creare un asset per il tema chiaro

 Non sono tanto a favore di mettere uno sfondo personalizzato nell'app, questo andrebbe a sostituire completamente lo sfondo traslucido gestito da windows, inoltre non creerebbe un'esperienza coerente con il resto delle app di windows.

2024-01-17 15:08 UTC, alessandrocaseti commented
> > ![Screenshot (257)](https://private-user-images.githubusercontent.com/90320229/291006177-c4eef2e9-ff00-41c0-8ba2-d5746ebb9b69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMDEzMTMsIm5iZiI6MTcwNTAwMTAxMywicGF0aCI6Ii85MDMyMDIyOS8yOTEwMDYxNzctYzRlZWYyZTktZmYwMC00MWMwLThiYTItZDU3NDZlYmI5YjY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDE5MjMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkNTVlYzEyZjIxOGM5MWM4MGJjNTVlMGMwOTQ3MWRlMWYzYTIyNmZiMzYzMDNmNzc4YTU1Y2NiMGUxN2U4NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WouAgrcx_8BXEX-JJo_0eWQSWQm7jRGB9LwghFbDlD8)
> > parte 1 pronta. Nella parte due - creare un asset per il tema chiaro
> 
> Non sono tanto a favore di mettere uno sfondo personalizzato nell'app, questo andrebbe a sostituire completamente lo sfondo traslucido gestito da windows, inoltre non creerebbe un'esperienza coerente con il resto delle app di windows.

ok lo toglierò nei prossimi giorni. Che ne dici di rilasciare la prossima versione a inizio febbraio?

2024-01-17 23:12 UTC, Gabboxl commented
> 
> ok lo toglierò nei prossimi giorni. Che ne dici di rilasciare la prossima versione a inizio febbraio?

Vediamo, c'è ancora tanta roba da fare

2024-03-03 16:50 UTC, Gabboxl requested changes

2024-03-03 16:50 UTC, Gabboxl commented on ClassevivaPCTO/Strings/it-it/Resources.resw
> +    <value>Codice studente:</value>
come nome utente è possibile mettere anche la mail, per cui "codice utente" non è del tutto corretto. se proprio lo vuoi cambiare mettiamo email/codice studente

2024-03-03 16:52 UTC, Gabboxl commented on ClassevivaPCTO/Views/LoginPage.xaml.cs
> +            EdittextPassword.Password = "test";
prima di fare il merge della pr fai un commit per togliere il pulsante dell'account demo, potrebbe confondere le persone, non si sa mai

2024-03-03 17:05 UTC, alessandrocaseti commented on ClassevivaPCTO/Strings/it-it/Resources.resw
> +    <value>Codice studente:</value>
ah scusa non ci avevo pensato, reverto subito

2024-03-03 17:07 UTC, alessandrocaseti commented on ClassevivaPCTO/Views/LoginPage.xaml.cs
> +            EdittextPassword.Password = "test";
ok

2024-03-04 20:34 UTC, Gabboxl commented
in mezzo c'è un relative panel con un contorno poco visibile, direi di toglierlo

2024-03-05 14:43 UTC, alessandrocaseti commented
@Gabboxl fatto

2024-03-05 19:07 UTC, Gabboxl commented
separiamo le animazioni nella pull request dedicata fino a quando non è pronto il sistema per disattivarle, inoltre credo si sia un po' complicata la pagina di login con troppi layout, dopo metto a posto

2024-03-05 19:33 UTC, Gabboxl commented
/rebase

2024-03-16 15:19 UTC, alessandrocaseti commented
@Gabboxl pronta per la review. Corretti i titoli dei dialog che non venivano indicizzati via XAML + metodi customresource

2024-03-17 21:11 UTC, Gabboxl approved these changes

2024-03-17 21:11 UTC, merged