optimized x:Uids + removed unused strings
Gabboxl/ClassevivaPCTO pull request #187
Opened 2023-11-12 14:25 UTC by alessandrocaseti

ottimizzate le traduzioni per evitare ridondanze e fare in modo che siano categorizzate secondo lo schema Pagina\Contenuto\Tipologia controllo. Rimosse le string inutilizzate.

2023-11-12 16:54 UTC, Gabboxl requested changes

2023-11-12 16:54 UTC, Gabboxl commented on ClassevivaPCTO/Strings/it-it/Resources.resw
> -  <data name="ButtonOpen.Text" xml:space="preserve">
se alcune stringe possono avere un nome generalizzato come "Apri" è da preferire, rispetto ad un nome specifico come ScrutiniOpenReportButton

2023-11-12 16:59 UTC, alessandrocaseti commented on ClassevivaPCTO/Strings/it-it/Resources.resw
> -  <data name="ButtonOpen.Text" xml:space="preserve">
come ho scritto nel commento aggiungerò dei tooltip legati agli uid

2023-11-13 18:33 UTC, Gabboxl requested changes

2023-11-13 18:33 UTC, Gabboxl commented on ClassevivaPCTO/Controls/ScrutiniListView.xaml
> +                        x:Name="ButtonOpenScrutinio" x:Uid="ScrutiniOpenFileButton" RelativePanel.LeftOf="ButtonSaveScrutinio"
x:Uid="ScrutiniOpenFileButton" è da togliere, il testo è già dentro lo stackpanel

2023-11-13 18:50 UTC, alessandrocaseti commented on ClassevivaPCTO/Controls/ScrutiniListView.xaml
> +                        x:Name="ButtonOpenScrutinio" x:Uid="ScrutiniOpenFileButton" RelativePanel.LeftOf="ButtonSaveScrutinio"
@gabboxl è il tooltip

2023-11-13 22:00 UTC, Gabboxl commented on ClassevivaPCTO/Controls/ScrutiniListView.xaml
> +                        x:Name="ButtonOpenScrutinio" x:Uid="ScrutiniOpenFileButton" RelativePanel.LeftOf="ButtonSaveScrutinio"
ah giusto, grazie

2023-11-13 22:00 UTC, merged