Localized short event codes, resource & UI updates, fixes strings
Gabboxl/ClassevivaPCTO pull request #223
Opened 2024-03-03 16:08 UTC by alessandrocaseti

- Fixed some margins
- Localized absence events short codes
- Fix: Ritardo breve () -> Ritardo breve
- Resource updates
- Added a bounch of new tooltips

2024-03-03 16:44 UTC, Gabboxl requested changes

2024-03-03 16:44 UTC, Gabboxl commented on ClassevivaPCTO/Utils/ApiValueAttribute.cs
non ti consiglio di gestire la traduzione degli eventi di assenza in questo modo, ogni messaggio associato ad un evento di assenza potrebbe non essere sempre lo stesso anche se il codice è il medesimo. da scuola a scuola potrebbe essere diverso, noi non possiamo saperlo, per cui è meglio non tradurlo

2024-03-03 16:47 UTC, Gabboxl commented on ClassevivaPCTO/Utils/ApiValueAttribute.cs
perchè tradurre i codici brevi? non ha senso, i codici brevi devono essere sempre visualizzati così come vengono restituiti dalla api

2024-03-03 17:16 UTC, Gabboxl commented on ClassevivaPCTO/Utils/ApiValueAttribute.cs
Tradurre i codici brevi creerebbe discrepanza con ciò che viene visualizzato di default nelle app ufficiali e agli insegnanti. tradurre il messaggio va bene se statico, ma il codice deve essere identico per tutte le app classeviva

2024-03-03 17:25 UTC, alessandrocaseti commented on ClassevivaPCTO/Utils/ApiValueAttribute.cs
In teoria l'utente dovrebbe essere consapevole che cambiando la lingua dell'app si potrebbero creare inconsistenze. E' ovvio che le traduzioni sono mirate a chi vuole imparare nuove lingue o chi si trasferisce per diversi motivi come gli erasmus e a questa categoria di persone non dovrebbe creare problemi. Come hai detto tu, di default l'app deve mostrare le stesse cose dell'app di Spaggiari, ed è quello che fa poiché le traduzioni sono un'opzione facoltativa. Secondo me, sono queste le piccole cose che fanno la differenza tra un client ufficiale ed uno di terze parti.

2024-03-03 17:46 UTC, Gabboxl commented on ClassevivaPCTO/Utils/ApiValueAttribute.cs
Per i messaggi degli eventi sono d'accordo a tradurli, però non per i codici tecnici.
Per esempio, se un utente dovesse segnalare un eventuale errore riguardo dei codici evento specifici, lui ci direbbe il codice tradotto nella sua lingua (se utente non italiano) e noi dovremmo innanzitutto capire la lingua del suo computer per poi andare a vedere quale codice tecnico reale restituito dall'API corrisponde al suo tradotto.
Anche se una situazione del genere è altamente improbabile che accada, è una possibile complicazione futura che ci stiamo creando. E' meglio non seguire questa prassi in generale, manteniamo separati i dati tecnici (che non devono essere tradotti e che servono per gli sviluppatori) e i messaggi testuali rivolti all'utente.

2024-03-04 19:09 UTC, Gabboxl commented on ClassevivaPCTO/Adapters/AbsenceEventAdapter.cs
a cosa serve questa modifica?

2024-03-04 20:21 UTC, alessandrocaseti commented on ClassevivaPCTO/Adapters/AbsenceEventAdapter.cs
perché sennò risulta Ritardo breve (), quindi toglie le parentesi inutili

2024-03-04 20:44 UTC, Gabboxl commented on ClassevivaPCTO/Adapters/AbsenceEventAdapter.cs
al posto di piazzare il controllo esclusivamente per i ritardi brevi controlliamo se il contenuto dentro le parentesi sia presente o meno, se è vuoto allora togliamo le parentesi, così funzionerà per tutti i casi

2024-03-04 20:47 UTC, alessandrocaseti commented on ClassevivaPCTO/Adapters/AbsenceEventAdapter.cs
riesci a farlo tu al volo? io sto cercando di fare le animazioni

2024-03-05 14:43 UTC, alessandrocaseti commented on ClassevivaPCTO/Adapters/AbsenceEventAdapter.cs
ho provato io ma nun funziona

2024-03-05 19:01 UTC, Gabboxl approved these changes

2024-03-05 19:01 UTC, merged