Code quality & string improvements, UI Updates, New palettes, Various fixes + reformat XAML
Gabboxl/ClassevivaPCTO pull request #249
Opened 2024-03-23 00:19 UTC by alessandrocaseti

closes: #241
closes: #246
closes: #240
implementato uno stile predefinito per le proprietà path e per i popup in agenda
aggiunto button chiudi flyout (notice)
commentati visualstate inutilizzati
aggiunte 2 nuove palette: Pastello e Vintage
implementate PRI resource delle lingue nuove #229
ottimizzati metodi e strings
tanti, ma tanti fix dell'UI
reformat XAML per views e dialogs

2024-03-23 09:56 UTC, Gabboxl requested changes

2024-03-23 09:56 UTC, Gabboxl commented on ClassevivaPCTO/ClassevivaPCTO.csproj
> +    <TargetPlatformMinVersion>10.0.18362.0</TargetPlatformMinVersion>
perchè alzare la versione minima di target?

2024-03-23 10:00 UTC, Gabboxl requested changes

2024-03-23 10:02 UTC, Gabboxl requested changes

2024-03-23 10:02 UTC, Gabboxl commented on ClassevivaPCTO/Controls/NiceNavigationView/NavigationView.Themeresources.xaml
togliamo le modifiche di formattazione a questo file, mi serve senza modifiche per confrontarlo con quello ufficiale di microsoft

2024-03-23 10:02 UTC, Gabboxl commented on ClassevivaPCTO/Controls/NiceNavigationView/NavigationView.xaml
togliamo le modifiche di formattazione a questo file, mi serve senza modifiche per confrontarlo con quello ufficiale di microsoft

2024-03-23 10:03 UTC, Gabboxl commented on ClassevivaPCTO/ClassevivaPCTO.csproj
> +    <TargetPlatformMinVersion>10.0.18362.0</TargetPlatformMinVersion>
scusa non hon letto l'ultima parte della pr, spero si possa evitare

2024-03-23 10:11 UTC, Gabboxl requested changes

2024-03-23 10:11 UTC, Gabboxl commented on ClassevivaPCTO/Views/AgendaPage.xaml
> +                <Style.Setters>
annulliamo le modifiche allo stile dei popup, se richiede una versione maggiore di windows molte persone resterebbero tagliate fuori
inoltre non credo porterebbe molti vantaggi di semplificazione centralizzare i controlli del relativepanel

2024-03-23 10:12 UTC, Gabboxl commented on ClassevivaPCTO/ClassevivaPCTO.csproj
> +    <TargetPlatformMinVersion>10.0.18362.0</TargetPlatformMinVersion>
annulliamo le modifiche ai popup e riportiamo la versione indietro

2024-03-23 10:14 UTC, Gabboxl requested changes

2024-03-23 10:14 UTC, Gabboxl commented on ClassevivaPCTO/Controls/NoticesListView.xaml.cs
non serve il pulsante chiudi per il flyout delle comunicazioni, basta premere al di fuori del flyout

2024-03-23 10:21 UTC, Gabboxl commented
se riesci magari la prossima volta cerchiamo di tenere separate le modifiche di formattazione e le nuove implementazioni in due pull request separate, così riesco a capire al volo cosa hai fatto di nuovo @alessandrocaseti

2024-03-23 17:10 UTC, Gabboxl commented
inoltre se in ambiti diversi, come issue che riguarda parti diverse dell'app, sapara il codice in pull request dedicate

2024-03-23 17:45 UTC, alessandrocaseti commented
@Gabboxl fatto tutto. Il messaggio di avviso che mi dava è 

XLS1105	La proprietà 'ShouldConstrainToRootBounds' nel tipo 'Popup' non è disponibile nella versione minima della piattaforma di destinazione (10.0.17763.0) supportata da questo progetto.	ClassevivaPCTO	C:\Users\alex0\Documents\GitHub\ClassevivaPCTO\ClassevivaPCTO\Views\AgendaPage.xaml	28	

lo ignoriamo?

poi, se riesci controlla le lingue come ti ho scritto alla fine della descrizione della pr

2024-03-23 17:51 UTC, Gabboxl commented
> @Gabboxl fatto tutto. Il messaggio di avviso che mi dava è
> 
> XLS1105 La proprietà 'ShouldConstrainToRootBounds' nel tipo 'Popup' non è disponibile nella versione minima della piattaforma di destinazione (10.0.17763.0) supportata da questo progetto. ClassevivaPCTO C:\Users\alex0\Documents\GitHub\ClassevivaPCTO\ClassevivaPCTO\Views\AgendaPage.xaml 28
> 
> lo ignoriamo?
> 
> poi, se riesci controlla le lingue come ti ho scritto alla fine della descrizione della pr

effettua un revert delle modifiche che hai fatto ai popup, lasciamo quella proprietà sull'oggetto

2024-03-23 18:00 UTC, alessandrocaseti commented
@Gabboxl fatto, ho anche corretto il margin del calendario assenze

2024-03-23 18:07 UTC, Gabboxl requested changes

2024-03-23 18:07 UTC, Gabboxl commented on ClassevivaPCTO/ClassevivaPCTO.csproj
reverta queste modifiche, il file csproj è generato automaticamente e verranno perse, metterò a posto io le stringhe più tardi

2024-03-23 18:14 UTC, Gabboxl requested changes

2024-03-23 18:14 UTC, Gabboxl commented on ClassevivaPCTO/Controls/NoticesListView.xaml.cs
se proprio vuoi mettere un pulsante "chiudi" per il flyout, mettiamolo come X in alto a sinistra

2024-03-23 18:18 UTC, Gabboxl commented on ClassevivaPCTO/Strings/it-it/Resources.resw
> +    <value>L'app non è stata tradotta completamente nella lingua che hai scelto. Alcune parti dell'app continueranno ad essere mostrate in questa lingua.</value>
le parti non tradotte verranno sempre mostrate in italiano

2024-03-23 18:25 UTC, Gabboxl requested changes

2024-03-23 18:25 UTC, Gabboxl commented on ClassevivaPCTO/Services/LocalizationResourcesService.cs
> +            {
non è il posto giusto per gestire le stringhe vuote, sarebbe da gestire dentro a ResourceExtensions.cs

2024-03-24 11:18 UTC, alessandrocaseti commented
direi che ci siamo, per quella cosa delle strings non saprei come fare

2024-03-24 11:21 UTC, Gabboxl commented
> direi che ci siamo, per quella cosa delle strings non saprei come fare

fai un revert, faccio io più tardi

2024-03-24 11:23 UTC, Gabboxl commented on ClassevivaPCTO/Controls/NoticesListView.xaml.cs
> +                    if (result == ContentDialogResult.Primary && !currentNotice.readStatus)
è necessario questo controllo?

2024-03-24 11:26 UTC, alessandrocaseti commented
> > direi che ci siamo, per quella cosa delle strings non saprei come fare
> 
> fai un revert, faccio io più tardi

eh ma dopo come fai con le path e le data? io ho trovato quel sistema che non credo dia problemi, casomai prova a farlo meglio come dicevi

2024-03-24 11:27 UTC, Gabboxl commented
> > > direi che ci siamo, per quella cosa delle strings non saprei come fare
> > 
> > 
> > fai un revert, faccio io più tardi
> 
> eh ma dopo come fai con le path e le data? io ho trovato quel sistema che non credo dia problemi, casomai prova a farlo meglio come dicevi

si lascia le strings, sarà rotto temporaneamente

2024-03-24 11:33 UTC, alessandrocaseti commented
ok

2024-03-24 18:30 UTC, alessandrocaseti commented
pronta

2024-03-24 21:23 UTC, Gabboxl approved these changes

2024-03-24 21:23 UTC, merged