minor UI updates
Gabboxl/ClassevivaPCTO pull request #40
Opened 2023-08-01 09:41 UTC by alessandrocaseti

2023-08-01 15:04 UTC, Gabboxl requested changes

2023-08-01 15:04 UTC, Gabboxl commented on ClassevivaPCTO/Views/LoginPage.xaml
> +                   HorizontalAlignment="Center" Margin="16" />
La versione direi di lasciarla a sinistra, non è rilevante

2023-08-01 15:04 UTC, Gabboxl commented on ClassevivaPCTO/Views/SettingsPage.xaml
>                              </StackPanel>
Meglio non usare i margin siccome non si adattano all'interfaccia, meglio un relativepanel

2023-08-01 15:18 UTC, alessandrocaseti commented on ClassevivaPCTO/Views/SettingsPage.xaml
>                              </StackPanel>
ok

2023-08-02 12:14 UTC, Gabboxl commented
unita

2023-08-02 12:14 UTC, closed without merging